name: Test Compiler
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  test_macos_aarch64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          cargo test test_compiler
  test_linux_aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run Tests
        run: |
          cargo test test_compiler

